### ISSUE TITLE
[Bug] Values on screen are not being updated

### ISSUE THREAD

**Issue by NoNameCola** [Phil1988/FreeDi#260]
The Q1 Pro display does not update it's temps, or even show the print status screen if you start a print thru the webUI instead of via the display. 

It should update to show current temps, and show the print progress screen regardless of how I start the print.

1. Start print using WebUI
2. Display does not update with temp values or show print progress screen. 

 - Q1 Pro
 - FreeDiLCD 2.00
 - Source: FreeDi 2.00 image
 - Mainboard: Stock Q1 Pro Mainboard.

**Comment by Phil1988** [comment]
It does work perfectly fine for me and many others.

Can you please provide a debug log?
https://github.com/Phil1988/FreeDi/wiki/Bugs!#are-there-any-bugs

**Comment by tekknix** [comment]
Interessting, i see the same behaviour on X PLUS 4, even if i do Filament-Unload / Load or change the Nozzle/Bed-Temp, it will not shown or updated on the Display. 

Even after a complete restart (Flashed eMMC, SD-Card, Toolhead...), the issue will be the same. Will try to collect a Debug-Log

Regards
MoS-tekknix

**Comment by tekknix** [comment]
Mhh, today in works without problems...

**Comment by Phil1988** [comment]
@NoNameCola 

Do you have addintional software installed like shaketune?
I have seen 5 reports where this was installed and slowed moonraker start to much.

Please try this:
```
sudo nano /etc/systemd/system/FreeDi.service
```
Change the delay to 10 (or if this is not enough to 15) at the following line:
```
ExecStartPre=/bin/sleep 10
```

**Comment by tekknix** [comment]
Have indeed set the Startup-Delay to 12Seconds and now regardless how often i'll start the Printer from Off-State, Firmware-Restart oder Klipper-Restart, Display is always working and in Sync with the WebGUI now.

**Comment by Phil1988** [comment]
@tekknix 
Do you have additional software installed like shaketune?

**Comment by tekknix** [comment]
Only Crowsnest and FLUIDD

**Comment by Phil1988** [comment]
Interessting! 
For me I dont have any reconnection issues at 5s.

**Comment by tekknix** [comment]
Maybe due to different Speed of the used eMMC? I've not done a speedtest and from my thoughts it seems to be more as sufficient:

mks@mkspi:~$ dd if=/dev/zero of=speedtest bs=64k count=10000 conv=fsync
10000+0 records in
10000+0 records out
655360000 bytes (655 MB, 625 MiB) copied, 5.84632 s, 112 MB/s

mks@mkspi:~$ dd if=speedtest of=/dev/null bs=64k count=110000000
10000+0 records in
10000+0 records out
655360000 bytes (655 MB, 625 MiB) copied, 5.63418 s, 116 MB/s

Anyhow, it's not really a problem to set it to 12s instead of 5s, cause normally i will start the printer only 1 or 2 times a day. 

So nothing to worry about.

**Comment by narfviper** [comment]
> [@NoNameCola](https://github.com/NoNameCola)
> 
> Do you have addintional software installed like shaketune? I have seen 5 reports where this was installed and slowed moonraker start to much.
> 
> Please try this:
> 
> ```
> sudo nano /etc/systemd/system/FreeDi.service
> ```
> 
> Change the delay to 10 (or if this is not enough to 15) at the following line:
> 
> ```
> ExecStartPre=/bin/sleep 10
> ```

Hi all,

I had the same issue on my Qidi X-Max3 with shaketune installed.
To increase the time like described above fixed it for me.

Thank you!

**Comment by Phil1988** [comment]
@NoNameCola @tekknix @narfviper 
Can someone with this problem (preferably with shaketune installed) test this and report if this works (this is one line that should replace the `ExecStartPre=/bin/sleep 10` line ):

Open the file via nano:
```
sudo nano /etc/systemd/system/FreeDi.service
```

then find the line starting with

`ExecStartPre=`

and replace it with:
```
ExecStartPre=/usr/bin/bash -c 'PORT=$(awk -F": " "/moonraker_port/ {print \$2}" /home/mks/printer_data/config/freedi.cfg); PORT=${PORT:-7125}; while ! echo > /dev/tcp/127.0.0.1/$PORT 2>/dev/null; do sleep 1; done'
````

**Comment by kingtricky** [comment]
I would just like to add ive got the same issue. I dont have shaketune installed. Only difference i have is beacon. Sometimes power cycling the printer helps. Ive tried the above fix, ill see how it goes.

**Comment by vaguirre-mx** [comment]
> [@NoNameCola](https://github.com/NoNameCola) [@tekknix](https://github.com/tekknix) [@narfviper](https://github.com/narfviper) Can someone with this problem (preferably with shaketune installed) test this and report if this works (this is one line that should replace the `ExecStartPre=/bin/sleep 10` line ):
> 
> ```
> ExecStartPre=/usr/bin/bash -c 'PORT=$(awk -F": " "/moonraker_port/ {print \$2}" /home/mks/printer_data/config/freedi.cfg); PORT=${PORT:-7125}; while ! echo > /dev/tcp/127.0.0.1/$PORT 2>/dev/null; do sleep 1; done'
> ```

I was having the same issue. This works for me on fresh install

Edit: Also works with shake&tune installed

**Comment by MicroSur** [comment]
The startup is normal, but there is no display of temperature changes and fan speed during printing!

**Comment by Phil1988** [comment]
I cant help without debug outputs :)

**Comment by pmbroth** [comment]
Hello Phil, I noted in discord the same, that  part fan and extruder temp, and chamber temps were not updating, and with me.  Also  after about an hour the chamber heater shut down.

**Comment by MicroSur** [comment]
> I cant help without debug outputs :)

I apologize. You can't just take and replace the names of the coolers, making them like in the usual stock configuration )))

**Comment by Phil1988** [comment]
@MicroSur 
So you renamed the fans to the weird stock "fan1 , "fan2" names? 😄
That does not work and the names are "suboptimal".

**Comment by WASP512** [comment]
I was having the same issue with a fresh install of FreeDi. I found how to fix the issue from the web interface. Go to the top right of the web portal and click the power button and click restart freedi, you will see the display rebooting and get stuck saying waiting on klipper, once it gets stuck at the end (I waited 2 minutes) I restarted klipper. Only took about 10 seconds after that and the display was back up with the correct information. 

I will pull logs the second this happens again. I just have a couple projects I need to keep printing so replicating this will come later

**Comment by MicroSur** [comment]
> [@MicroSur](https://github.com/MicroSur) So you renamed the fans to the weird stock "fan1 , "fan2" names? 😄 That does not work and the names are "suboptimal".

```
freedi				original & openq1

fan					cooling_fan
sidefan 			auxiliary_cooling_fan
chamber_heater_fan	chamber_fan
hotend_fan			hotend_fan
filterfan			chamber_circulation_fan
hotend_fan2			hotend_fan2
Mainboard_fan		board_fan
```

**Comment by Phil1988** [comment]
@MicroSur 
It doesnt matter that much how QIDI or anyone else named different objects.
FreeDi has to identify the parts and as QIDI is not consistent and not clear on names over the time, you have to stick with my naming convention or use a stock system.

**Comment by chrashing** [comment]
Hello Phil,   (Edit corrected spelling to single 'L' . Sorry.) 

Started printer with my original settings from issue 298
ssh'd in and started debug

From Moonraker   changed CHAMBER target to 40C      (printer display did not echo target update.)
From Moonraker  changed BED target to 40C                 (printer display did echo target update)
       -- note that I reversed from CHAMBER, BED to BED, CHAMBER order below --.
From printer Display changed BED target to  0C             (printer display did  echo target update.)
From printer Display  changed CHAMBER  target to 1C  (printer display did echo target update)           

Collected the following:

Last login: Fri Jul 25 20:06:43 2025 from 192.168.68.77
mks@mkspi:~/FreeDi/FreeDiLCD$ sudo systemctl stop FreeDi.service
cd ~/FreeDi/FreeDiLCD && sudo ~/klippy-env/bin/python3 start.py -debug
[sudo] password for mks:
[MainThread] Section [freedi] not found in the printer.cfg.
[MainThread] Using freedi.cfg instead of printer.cfg.
[Thread-1 (monitor_updates)] Connecting to Moonraker at ws://127.0.0.1:7125/websocket
[MainThread] self.user_name: mks
[MainThread] self.user_group: mks
[MainThread] TFT baudrate detection...
[Thread-1 (monitor_updates)] Websocket connected
[Thread-1 (monitor_updates)] Moonraker connection opened at ws://127.0.0.1:7125/websocket
[MainThread] Detected baudrate: 921600
[MainThread] Detected display model: TJC8048X250_011R
[Thread-1 (monitor_updates)] File name was reset
[Thread-1 (monitor_updates)] Updating print stats with state: standby
[Thread-1 (monitor_updates)] Getting metadata with state: standby, current printer state: None
[Thread-1 (monitor_updates)] Printer state updated: standby
[Thread-1 (monitor_updates)] G-Code file path is: ~/printer_data/gcodes
[MainThread] Display firmware: v2.00
[MainThread] LCD firmware is OK
[MainThread] Waking up LCD...
[MainThread] Monitoring is already running.
Software version: v2.00 stable
[MainThread] Printer model: unknown
[MainThread] Printer volume: 328x326x322
[MainThread] Klipper version: v0.13.0-154-g9346ad19-dirty
[MainThread] FreeDiLCD start
[MainThread] FreeDi sw-version sent to screen!
[Thread-6 (dynamic_lcd_update)] klippy ready
[Thread-6 (dynamic_lcd_update)] Printer in standby
[Thread-6 (dynamic_lcd_update)] Forwarding to main
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] _TempPages: len: 1 data[0]: 2
[ThreadPoolExecutor-0_0] ActiveScreen: = MainTempBedPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] CMD_TEMP command received
[ThreadPoolExecutor-0_0] _NewTempBedPage: len: 1 data[0]: 0
[ThreadPoolExecutor-0_0] _NewTempBedPage: Data received: 0
[ThreadPoolExecutor-0_0] printer_callback triggered
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] _TempPages: len: 1 data[0]: 3
[ThreadPoolExecutor-0_0] ActiveScreen: = MainTempChamberPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] CMD_TEMP command received
[ThreadPoolExecutor-0_0] _NewTempChamberPage: len: 1 data[0]: 1
[ThreadPoolExecutor-0_0] _NewTempChamberPage: Data received: 1
[ThreadPoolExecutor-0_0] printer_callback triggered
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage

**Comment by chrashing** [comment]
Continuing to follow up from issue 298,
 
Changed:
sudo systemctl stop FreeDi.service
cd ~/FreeDi/FreeDiLCD && sudo ~/klippy-env/bin/python3 start.py -debug

powered off/on printer, and followed the same procedure as my previouse post with the same target display value results. 

Below is the resulting log:

mks@mkspi:~/FreeDi/FreeDiLCD$ sudo systemctl stop FreeDi.service
cd ~/FreeDi/FreeDiLCD && sudo ~/klippy-env/bin/python3 start.py -debug
[MainThread] Section [freedi] not found in the printer.cfg.
[MainThread] Using freedi.cfg instead of printer.cfg.
[Thread-1 (monitor_updates)] Connecting to Moonraker at ws://127.0.0.1:7125/websocket
[MainThread] self.user_name: mks
[MainThread] self.user_group: mks
[MainThread] TFT baudrate detection...
[Thread-1 (monitor_updates)] Websocket connected
[Thread-1 (monitor_updates)] Moonraker connection opened at ws://127.0.0.1:7125/websocket
[Thread-1 (monitor_updates)] File name was reset
[Thread-1 (monitor_updates)] Updating print stats with state: standby
[Thread-1 (monitor_updates)] Getting metadata with state: standby, current printer state: None
[Thread-1 (monitor_updates)] Printer state updated: standby
[Thread-1 (monitor_updates)] G-Code file path is: ~/printer_data/gcodes
[MainThread] Detected baudrate: 921600
[MainThread] Detected display model: TJC8048X250_011R
[MainThread] Display firmware: v2.00
[MainThread] LCD firmware is OK
[MainThread] Waking up LCD...
[MainThread] Monitoring is already running.
Software version: v2.00 stable
[MainThread] Printer model: unknown
[MainThread] Printer volume: 328x326x322
[MainThread] Klipper version: v0.13.0-154-g9346ad19-dirty
[MainThread] FreeDiLCD start
[MainThread] FreeDi sw-version sent to screen!
[Thread-6 (dynamic_lcd_update)] klippy ready
[Thread-6 (dynamic_lcd_update)] Printer in standby
[Thread-6 (dynamic_lcd_update)] Forwarding to main
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] _TempPages: len: 1 data[0]: 2
[ThreadPoolExecutor-0_0] ActiveScreen: = MainTempBedPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] CMD_TEMP command received
[ThreadPoolExecutor-0_0] _NewTempBedPage: len: 1 data[0]: 0
[ThreadPoolExecutor-0_0] _NewTempBedPage: Data received: 0
[ThreadPoolExecutor-0_0] printer_callback triggered
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] _TempPages: len: 1 data[0]: 3
[ThreadPoolExecutor-0_0] ActiveScreen: = MainTempChamberPage
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] Received touch during awake, resetting dim timer
[ThreadPoolExecutor-0_0] CMD_TEMP command received
[ThreadPoolExecutor-0_0] _NewTempChamberPage: len: 1 data[0]: 1
[ThreadPoolExecutor-0_0] _NewTempChamberPage: Data received: 1
[ThreadPoolExecutor-0_0] printer_callback triggered
[ThreadPoolExecutor-0_0] _NewMainPage: len: 1 data[0]: ee
[ThreadPoolExecutor-0_0] ActiveScreen: = MainPage

**Comment by Potatonater5001** [comment]
If it helps at all, I have noticed something similar to this "desync" on my xplus3 before, but only after I had run SAVE_CONFIG and klipper was restarted. This has always been fixed by simply doing a full system reboot after doing anything requiring SAVE_CONFIG for klipper. 

I'm sure this isn't very helpful in terms of debugging, and is an annoying and time consuming solution, but it may be a good enough temporary workaround for people until the actual problem is found.

**Comment by Phil1988** [comment]
This is not a solution, but as a workaround, you can simply restart FreeDi instead of the whole printer:

<img width="901" height="437" alt="Image" src="https://github.com/user-attachments/assets/ae010206-83e2-41fe-bcbb-d0abed694aa1" />

In the next days I will use the printer more and see if I can reproduce this bug.
If anyone finds a good way how to get this bug - please let me know :)

**Comment by Phil1988** [comment]
@NoNameCola  @tekknix @chrashing @Potatonater5001 
Can you confirm weather or not it is still existent with V2.01?

**Comment by narfviper** [comment]
> [@NoNameCola](https://github.com/NoNameCola) [@tekknix](https://github.com/tekknix) [@narfviper](https://github.com/narfviper) Can someone with this problem (preferably with shaketune installed) test this and report if this works (this is one line that should replace the `ExecStartPre=/bin/sleep 10` line ):
> 
> Open the file via nano:
> 
> ```
> sudo nano /etc/systemd/system/FreeDi.service
> ```
> 
> then find the line starting with
> 
> `ExecStartPre=`
> 
> and replace it with:
> 
> ```
> ExecStartPre=/usr/bin/bash -c 'PORT=$(awk -F": " "/moonraker_port/ {print \$2}" /home/mks/printer_data/config/freedi.cfg); PORT=${PORT:-7125}; while ! echo > /dev/tcp/127.0.0.1/$PORT 2>/dev/null; do sleep 1; done'
> ```

Sorry I just saw your post.

I was updating to FreeDi 2.01 2 days ago, had no problem after update.
Yesterday I installed shaketune again, without any problem so far.

As far as I can see you have already entered the line above in the FreeDi.service config.

I have done a few powercycles of the printer and never had an issue with the display so far.
I will continue to monitor the situation.

**Comment by Phil1988** [comment]
Yes I included all the fixes on v2.01 already.

Very nice to hear that it all wors flawless for you even after installing S&T 👍

**Comment by Phil1988** [comment]
Because of low activity of the OP and the reports that this is not existent anymore on v2.01, I am closing this :)
