### ISSUE TITLE
[Bug] X-Smart 3 Input Shaper Not Working After Update

### ISSUE THREAD

**Issue by robonxt** [Phil1988/FreeDi#309]
**Describe the bug**
After updating the system and other parts such as moonraker, klipper, etc, I am no longer able to use the input shaper on my X-Smart 3

**Expected behavior**
Input shaper should be working on updated things.

**To Reproduce**
Update to latest everything, run Input Shaper from display.

**Extra Information**
I recall seeing in changelogs that moonraker, kipper, mainsail have major updates since the release of FreeDI v2.00

**Console output**
If applicable, add the debug console output here (here is a [how to](https://github.com/Phil1988/FreeDi/wiki/Bugs!))

**Base (please complete the following information):**
 - Printer model: X-Smart 3
 - X3seriesLCD firmware version: v2.00-0-g0663905e
 - Source: FreeDi image
 - Mainboard: Stock firmware

**Other**
There is also an issue with thumbnails not being centered and being cropped on the display even though I followed the recommended steps in the wiki.

**Comment by Phil1988** [comment]
Thanks for the report.
Can you tell me the error message you get?

About the thmbnails: 
Set it to `150x150/PNG, 48x48/PNG`?

**Comment by robonxt** [comment]
Huh, seems like it's working now after I loaded the default macros. Weird, it was not working yesterday. Perhaps it needed a full system restart. 

As for the thumbnail, I cannot test it due to #310 preventing me from printing.

**Comment by Phil1988** [comment]
I am sure your macros.cfg was pretty faulty and also the reason for this.
Now as https://github.com/Phil1988/FreeDi/issues/310 is solved I hope this is also gone.

Please check and verify this.

**Comment by robonxt** [comment]
Input shaper is working (I'll need to test it again later when I'm not using it)

Thumbnails are still not correct though, seems like the display isn't showing it centered, and it is also getting out of sync with the information from the printer (shows previous print info instead of current, eta time not the same as mainsail web, etc)

**Comment by Phil1988** [comment]
Please dont mix issues ;)

I close this now as it is solved and was no bug (so I will rename this thread).

The 2nd issue about the thumbnail:
Did you change the slicer accordingly?
If yes, please open a new one.

The 3rd issue you mentioned is already opened (and fixed, but not released/pushed yet).

**Comment by robonxt** [comment]
Just an update: 

input shaper is working now. Config was probably not working like you suggested.  I've pulled from the latest update and it's not bugging me anymore.

Thumbnails are also working at the moment, most likely a slicer issue.

**Comment by Phil1988** [comment]
Thanks for keeping me updated @robonxt 👍
