### ISSUE TITLE
[Bug] WiFi Password Char Limit

### ISSUE THREAD

**Issue by my2kta** [Phil1988/FreeDi#344]
Issue:
During the initial setup, when attempting to enter my Wifi password (16 char) the field appears to be limited to 14 chars.  When pressing any key beyond the 14th entry, the screen does not update.   Unsure if special characters are to blame, ex:  Aaaaaa.1111:Bbbb

Complete fresh install and begin Wizard.
1.  When at Wifi network screen, select SSID.
2.  Begin typing characters or string that is 16 char or longer.
3.  Observe if screen continues to update past the 14th character.

Q1 Pro.

I prefer to use the ethernet connection so this is not a blocker for me, but I noticed this behavior in both v2.0 and v2.0.1.  I have not attempted to connect to the WiFi post setup wizard.

**Comment by Phil1988** [comment]
Thanks for the report!

I can confirm this bug for the Q1 and for the Smart3 (others being not affected) on the wizard wifi config only (the real network manager is OK).

I fixed it and it will be included in the next release.
Once released, I will ping you to kindly check if it is still present before I close this :)

**Comment by Scrumplex** [comment]
I have just installed FreeDi on my Q1 and I noticed that I wasn't able to enter `^` for the WiFi psk. I assume this is another thing that needs to be added to the display's keyboard.

I was able to do it through nmcli ofc!

**Comment by wildy** [comment]
I just flashed FreeDI onto my XMAX 3, and wasn't able to connect at all -- turns out that the string that ends up in `/etc/NetworkManager/system-connections/*.nmconnection` gets truncated. Had to choose another network, SSH into the printer and edit the nmconnection myself.

**Comment by Phil1988** [comment]
@Scrumplex you are right.
I will add it and include it with the next release.


@wildy Is yours different from the OPs report?

**Comment by wildy** [comment]
> [@Scrumplex](https://github.com/Scrumplex) you are right. I will add it and include it with the next release.
> 
> [@wildy](https://github.com/wildy) Is yours different from the OPs report?

Yes, I think this is a different problem. The password in the connection file gets truncated.

**Comment by Phil1988** [comment]
> Yes, I think this is a different problem. The password in the connection file gets truncated.

How many characters will it be truncated to?

**Comment by wildy** [comment]
> > Yes, I think this is a different problem. The password in the connection file gets truncated.
> 
> How many characters will it be truncated to?

I would have to replicate this again, since I got it to work successfully by editing the `.nmconnection` file directly. Expect this to be done tomorrow -- I will be near the printer.

**Comment by Phil1988** [comment]
I just [released v2.01](https://github.com/Phil1988/FreeDi/releases/tag/v2.02) and it would be very nice if anyone of you @my2kta @Scrumplex @wildy could confirm it is solved :)

**Comment by Haegar333** [comment]
@Phil1988 

Did you probably do a mishap and upload the new v2.02 on the v2.01 entry?

**Comment by Phil1988** [comment]
@Haegar333 
I am just a regular guy and definetly do mistakes, but can you please clarify what you mean?
I see the v2.02 for the release and the screen firmwares, also with correct tags:

<img width="194" height="102" alt="Image" src="https://github.com/user-attachments/assets/13fe8dc6-9ca0-4aa7-bdfb-b3472aed4b3f" /><br>

<img width="591" height="54" alt="Image" src="https://github.com/user-attachments/assets/3415fb2f-e77d-492b-9081-751ea82e9536" /><br>

<img width="856" height="334" alt="Image" src="https://github.com/user-attachments/assets/e7c7c4f1-ffd3-4951-a967-7b968adb4044" />

**Comment by Haegar333** [comment]
@Phil1988 

Thank you for your prompt answer and your work on this project.

I, as a firmware noob, was looking for the image. That's the reason I was asking.

**Comment by Phil1988** [comment]
Thanks mate - I do my best :)
It would be nice if you can ask questions like this preferebly via discord (faster responses from users and me) or via a seperate thread just to keep this clean ;)

For your question, please use v2.01 (it has a full image) as basis and update from there to v2.02.
And welcome to the family :)

**Comment by Phil1988** [comment]
I am closing this due to inactivity (and because I am positive that this is fixed).

**Comment by Haegar333** [comment]
I flashed 2.06 right now.

I don't know if I misunderstood this, but I still cannot insert a WIFI pass longer than 12 letters/numbers.

**Comment by Phil1988** [comment]
@Haegar333 You didnt misunderstood this.
It is supposed to be fixed, but as it is not for you, can you please tell me what printer model you have and where you are trying to enter the passwortd? (from the wizard or at the settings->network manager?)

**Comment by Haegar333** [comment]
@Phil1988 

Smart X3

Fresh image, first startup, in the Wizard

Edit: 2.06

**Comment by Phil1988** [comment]
Thanks @Haegar333 
Do you have access to your printer right now via ssh terminal (eg. via ethernet cable, changing the wifi password temporarly orsomething?)

**Comment by Haegar333** [comment]
Sorry, not today. The printer is right behind me, but I am busy with work right now

**Comment by Haegar333** [comment]
So, I opened another WIFI network with a short password.

I cannot save the password, or better, after typing it, after clicking OK on the osk, I am back at the WIFIs overview, and nothing changed.

After several unsuccessful tries, I went on.

Now the printer is blocked at Klipper reports error.

**Comment by Haegar333** [comment]
I reupdated the MCU, nothing. Reboot several times, nothing.

Rewrote img, nothing. 2 times reboot, now i am at a working printer,

In the settings long WIFI password worked.

**Comment by Phil1988** [comment]
@Haegar333 
It was likely somy python caching issue.
I had this just the other day :)

So on the wizard the wifi connection couldnt be established, but on the normal network manager (at the "gear" menu and then to the network) it is possible?
Thats really odd.
I tested it a few times on my end, but it simply always works.
Can you re-check this after updating to [v2.08](https://github.com/Phil1988/FreeDi/releases/tag/v2.08)?

**Comment by Phil1988** [comment]
Closing because of inactivity
