### ISSUE TITLE
[Bug] Q1: setting chamber temp changes bed temp on printjob screen

### ISSUE THREAD

**Issue by andreykurichev** [Phil1988/FreeDi#351]
@Phil1988

Hello, I noticed an error: if you change the temperature of the thermal chamber on the display during printing, it will not the temperature of the chamber, but the temperature of the heating table.

Printer: Qidi Q1

Freedi: 2.01

System image from Freedi 2.00

I updated Freedi to 2.01, but did not overwrite the emmc file; image from the previous version, 2.00.

Failed to download the video, sorry.

I wanted to upload it to YouTube, but I was told to wait for the time. Maybe I'm from Russia. I don't know. Sorry

**Comment by Phil1988** [comment]
Thanks for the report.
Vega already reported this on discord and I fixed it.
I will publish a new release when I am back home again :)

Btw: I recommend you rewrite the EMMC with v2.01 as it's based on another OS that doesn't has the system freeze bug.

Cheers!

**Comment by dewi-ny-je** [comment]
Is the release coming soon?

**Comment by Phil1988** [comment]
@dewi-ny-je 
Yes, I am already at testing and do some final tweaks for the configs.
Shouldnt take many days :)

**Comment by Phil1988** [comment]
@andreykurichev @dewi-ny-je 
Please check out the [latest release](https://github.com/Phil1988/FreeDi/releases/tag/v2.02) that I just published and tell me if this solves it for you :)

**Comment by dewi-ny-je** [comment]
Waiting for the emmc reader

**Comment by Phil1988** [comment]
Any news on that @andreykurichev @dewi-ny-je ?

**Comment by dimbas80** [comment]
The problem still persists.
When setting the chamber temperature, the table temperature setting also changes, but only on the screen. The actual table setting doesn't change in the web interface, and the table continues to heat up to the desired temperature.

![Image](https://github.com/user-attachments/assets/79df71c4-e285-4af5-9ee7-6a6d28c6ca91)

**Comment by Phil1988** [comment]
Thanks for the details!
That made it easier for me to find that leftover.
I fixed it and it will be enrolled with the next release.
Meanwhile it should only be cosmetical as the temperatures being set correctly but the display shows the the chamber temp at the bed temp if you change that while printing from display.

I'll ping you once its being released 👍

**Comment by andreykurichev** [comment]
@Phil1988 Sorry, I haven't logged into GitHub in a while, and the problem persists. Now it only changes on the display, everything is fine in the web interface.

![Image](https://github.com/user-attachments/assets/d3181548-832f-48bd-b7d1-b17aba6ed8ac)

![Image](https://github.com/user-attachments/assets/b701f29c-9b98-4a51-8bb3-9a3a89288e13)

**Comment by dimbas80** [comment]
> [@Phil1988](https://github.com/Phil1988)Извините, я давно не заходил в GitHub, и проблема сохраняется. Теперь изменения происходят только на экране, в веб-интерфейсе всё в порядке.
> 


Are you sure you have the latest firmware version? I'm fine. I just checked.

**Comment by andreykurichev** [comment]
@dimbas80 

![Image](https://github.com/user-attachments/assets/827e819f-a34f-46ec-b9ce-1530d44904ab)

**Comment by Phil1988** [comment]
@andreykurichev I tested it for more then one hour and checked the code an additional hour but couldn't find/replicate this issue.

Can you please do a short video how you can get this error?

**Comment by andreykurichev** [comment]
This happens if you run a print without preheating the thermal chamber, and then add the thermal chamber temperature (from the screen) during printing. I checked a second time, and it happened. Again, excuse my English, it's Google Translate.

**Comment by Phil1988** [comment]
@andreykurichev 
That was one of the cases I tested several times on my side and one additional time after I read your post.
I am starting to get crazy, doing the same and hope to see a different outcome :D

So for me it really just works in any condition and case I could think of.
As I released v2.08, maybe that solves it for you.
I would be surprised tho, as I didnt change anything :D

**Comment by Phil1988** [comment]
Closed due to no feedback and inactivity.
Feel free to reopen, when still present with the latest release :)
