### ISSUE TITLE
[Not a bug] Forgot to flash the mainboard mcu / toolhead

### ISSUE THREAD

**Issue by Caretaker61** [Phil1988/FreeDi#79]
**Describe the bug**
Hello,
I am new to this and have recently purchased a QIDI-X-MAX 3 and to date I cannot work with it.
QIDI support has given me countless tasks and already sent me two new emmc, but the printer refuses to work.
I flashed FreeDi v1.30 onto the emmc yesterday and get the following display:
Klipper meldet: ERROR

MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

Your Klipper version is: v0.12.0-289-g08a1c9f12-dirty
MCU(s) which should be updated:
mcu: Current version v0.10.0-530-g3387a9c2-dirty-20221121_013639-mkspi
MKS_THR: Current version v0.10.0-530-g3387a9c2-dirty-20221210_215217-mkspi
Up-to-date MCU(s):
<none>

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.

mcu 'MKS_THR': Command format mismatch: query_adxl345 oid=%c rest_ticks=%u vs query_adxl345 oid=%c clock=%u rest_ticks=%u

What do I have to do to reinstall the system or how I can solve this problem?

**Base (please complete the following information):**
 - X3seriesLCD firmware version: ??
 - OS: FreeDi_v1.30_X-Max3_Armbian24.2.0_Bookworm6.6.17
 - Source: FreeDi image
 - Mainboard: X-6 V1.0
[moonraker.log](https://github.com/user-attachments/files/18429233/moonraker.log)

**Comment by Phil1988** [comment]
You missed this [part](https://github.com/Phil1988/FreeDi/wiki/Installation-guide-for-fresh-systems#flashing-the-mainboard-mcu)
![image](https://github.com/user-attachments/assets/2c4c51c4-668f-4cf6-bc97-17763ca86519)

Fortunately its a very easy thing to solve for you :)

Please report back how it worked out ;)

**Comment by pmbroth** [comment]
@Phil1988   I was typing when your message popped up.    :-)

**Comment by Phil1988** [comment]
> @Phil1988 I was typing when your message popped up. :-)

first!

**Comment by Caretaker61** [comment]
Done, but the same error. The file is changed to X_4.CUR

**Comment by Phil1988** [comment]
I can only help if you give me more information

I don't think it's the same error.
You probably getting the MCU reported as Klipper
v0.12.0-289-g08a1c9f12-dirty.
And you probably don't read further and flashed the tool head, did you?

Please read the whole guide mate 🙏 
There is a reason I took my time to write this down 😃

**Comment by Caretaker61** [comment]
Hi Phill,
sorry, but I didn't have a good day yesterday.
I followed your instructions and now also flashed the motherboard mcu and the tool head.
Now I get this on the LCD screen of the printer:
![image](https://github.com/user-attachments/assets/eee0c994-2381-4b8c-a9b5-43f03cd55189)


and in Moonraker this:
Klipper meldet: ERROR

mcu 'MKS_THR': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

I restart the printer and wait 2 minutes and restart them, but nothing changed.
I tried to get the device ID via SSH, but I get the following output:
mks@mkspi:~$ ls /dev/serial/by-id/*
ls: cannot access '/dev/serial/by-id/*': No such file or directory

**Comment by Caretaker61** [comment]
I tried to read out the error using your instructions:

mks@mkspi:~$ sudo systemctl stop FreeDi.service
[sudo] password for mks:
mks@mkspi:~$ cd ~/FreeDi/FreeDiLCD && ~/klippy-env/bin/python3 start.py -debug
Connecting to Moonraker at ws://127.0.0.1:80/websocket
Moonraker host address: http://127.0.0.1:80
Using selector: EpollSelector
TFT baudrate detection...Websocket connected
G-Code file path is: ~/printer_data/gcodes
Found z_offset = 1.549 in variable "z_offset" in section "probe"
Detected baudrate: 921600
Display response: comok 1,1281-0,TJC8048X250_011R,165,10201,CEB33401F645C95A,33554432-0
Display firmware: v1.30
Printer model: x-max3
Printer volume: 328x326x322
Klipper version: v0.12.0-289-g08a1c9f12-dirty
Software version: v1.30 stable
FreeDiLCD start
FreeDi sw-version sent to screen!
self.lcd.data_update()
data.klipper_state != self.printer.klipper_state
klippy error
_NewConnectionLostPage: len: 1 data[0]: ee
ActiveScreen: = ConnectionLostPage
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()
self.lcd.data_update()

I cancelled the command after a while because the same message kept appearing.

**Comment by Phil1988** [comment]
Its not a display or FreeDi software issue.
Your toolhead is not ready or incorrectly configured in klipper.

Please show me what you get at the Machine-> System Loads tab in Mainsail.
Should be something like this.
![image](https://github.com/user-attachments/assets/0ca60999-c92d-49dc-a557-c63a75d27732)

**Comment by Caretaker61** [comment]
I did not find the system load in mainsail, see attached picture.
![2025-01-16 12_22_33-ERROR](https://github.com/user-attachments/assets/bf8e3d07-7da9-4a01-a405-94107cee110d)
[printer.zip](https://github.com/user-attachments/files/18438662/printer.zip)

**Comment by Phil1988** [comment]
Thanks for that!

Unfortunately, I cannot understand the problem. 
Since you could previously see the toolhead (MKS THR) as klipper `v0.10.0-530-g3387a9c2-dirty-20221210_215217-mkspi`, you should now be able to see your freshly flashed toolhead at 
```
mks@mkspi:~$ ls /dev/serial/by-id/*
```

For me there are currently 2 possible reasons:
1. The toolhead has hung up (boot cycle with power off solves this)
2. The wrong firmware was flashed to the toolhead.

Please give me feedback on this, because it looks to me as if information is missing here.

**Comment by Caretaker61** [comment]
Phil,
what did you mean with "boot cycle with power off solves this" ?

**Comment by Caretaker61** [comment]
I install the firmware again, as you wrote in your instruction.
Firmware "Toolhead_RP2040.uf2" is installed

**Comment by Caretaker61** [comment]
same result

**Comment by pmbroth** [comment]
You either did not flash the onboard mcu with the micro sd card, and/or you did not do the flash to the tool head.  Both need to be the version that Phil has in this directory

https://github.com/Phil1988/FreeDi/tree/master/mainboard_and_toolhead_firmwares/v0.12.0-289

**Comment by Caretaker61** [comment]
I flash the mcu again with V_4.bin. After flashing the file was renamed to V_4.CUR. Is that correct or an error?
During the flashing I see no reaktion on the Printer-Screen, is that also correct?

**Comment by pmbroth** [comment]
Yes that is correct.   You have to do the tool head..  Make sure it is in flashmode utilizing Phils instrucitons

**Comment by Phil1988** [comment]
> Phil, what did you mean with "boot cycle with power off solves this" ?

I mean a shutdown with the switch shut off (so that no component gets power).



> I flash the mcu again with V_4.bin [...] V_4.CUR

Its X_4.bin and X_4.CUR so just a typo I guess, but yes: if its renamed to *.CUR it was flashed.

Now focus on the tool head.
Show us screenshots and provide more information please.
"same result" and "it doesnt work" does not help us to help you :)

You are doing something wrong, but if you dont tell us **exactly** what you do, we cant see what is wrong ;)

**Comment by EisbacherG** [comment]
Hello Phil.
I get the same error.
i have done everything as it is described in your wiki.
MCU is flashed with downloaded X_4.bin
Toolhead is flashed with downloaded .uf2 file.

![Image](https://github.com/user-attachments/assets/1f2cc8e1-e11e-4914-a206-5a1a378aa033)

**Comment by Caretaker61** [comment]
Hello,
the printer is now running without error messages.
Yesterday I updated the MCU and the tool head again and disconnected the printer from the power supply overnight. This morning I switched the power supply back on and started up the printer and, lo and behold, everything was ok!!!!!
Many thanks to Phil and everyone else who helped me.
I am a complete novice in this area and I hope I haven't annoyed you with my ignorance
Can I contact you again if I have a ‘problem’ with the printer or software?
Again many thanks!

**Comment by Phil1988** [comment]
> [...] disconnected the printer from the power supply [...]. everything [is] ok!!!!! Many thanks to Phil and everyone else who helped me. I am a complete novice in this area and I hope I haven't annoyed you with my ignorance Can I contact you again if I have a ‘problem’ with the printer or software? 

So it really was only a problem flashing the mcu and toolhead and then a simple power cycle solved it 👍 
Im not annoeyd at all and invite you to contact me again if you face any problems :)
Im glad its working for you now! 
Happy printing :)

**Comment by Caretaker61** [comment]
Hi Phill,
I wrote to you this morning to say that the same problem as described here had been fixed, but it occurred again after the printer was restarted.

3rd result ls /dev/serial/by-id/* 

![Image](https://github.com/user-attachments/assets/b7a4338a-5350-48c4-8cb6-b62b73120bf7)


4th result lsusb

![Image](https://github.com/user-attachments/assets/1675814d-50fb-40a7-872d-a7598679ad3b)


5th result lsblk

![Image](https://github.com/user-attachments/assets/923f35a9-8fc6-4e6f-a314-7015980cb9b9)




Please find attached the printer.cfg file
[printer.zip](https://github.com/user-attachments/files/18452826/printer.zip)

**Comment by Phil1988** [comment]
Problem is that your toolhead is not recocnized.
Have you seen a partition with 128MB in the past before you tried to flash it?

Something like this, but maybe named as sdb1:
![image](https://github.com/user-attachments/assets/0058e949-23e1-4f4b-8388-1c25fcb4c9d2)


It seems to me like to be a hardware issue.
Have you had any problems with the toolhead in the past?

My best guess right now is either:
your toolhead is defective
or the cable to the toolhead has a loose contact/is faulty.


Besides that you have a wifi dongle in usb mode like this
https://github.com/Phil1988/FreeDi/issues/23

Lets do an install to install the wifi dongle, but I would be very surprised if this solves the issue with the toolhead:
```
cd ~/FreeDi && ./install.sh
```
Show me the while output please :)

**Comment by Caretaker61** [comment]
Phill,
I try to install the WLAN with "cd ~/FreeDi && ./install.sh" and get the question "Do you use the stock Mainboard? (y/n)"
What must I answer?

**Comment by Caretaker61** [comment]
I answer with "y". The installtion is finished, I checked the the cable to the toolhead and I restart the printer.
But I get the same message:
Klipper reports: ERROR

mcu 'MKS_THR': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

Can I restore the printer to its factory settings?

**Comment by Phil1988** [comment]
The answer "y" (yes) was correct for you.

You forgot to 
`Show me the whole output please :)`
`Have you seen a partition with 128MB in the past before you tried to flash it?`
`Have you had any problems with the toolhead in the past?`
I am still missing the answers to my questions, so I dont know how I should help you :(

You can roll back to your stock system if you want to, but I am sure, that the hardware issue will remain.
Should I tell you how to go back to stock or do we proceed?

**Comment by rosenrot00** [comment]
> I answer with "y". The installtion is finished, I checked the the cable to the toolhead and I restart the printer. But I get the same message: Klipper reports: ERROR
> 
> mcu 'MKS_THR': Unable to connect Once the underlying issue is corrected, use the "FIRMWARE_RESTART" command to reset the firmware, reload the config, and restart the host software. Error configuring printer
> 
> Can I restore the printer to its factory settings?

Besides the output that is still missing and if you like to proceed - issues are solved more easily when they are broken down into smaller pieces. Let's go step by step to identify your issue.

Scenario A:
1. Remove any attached USB drive
2. Start your printer just normally
3. Provide the output of "lsusb", "lsblk" and "ls /dev/serial/by-id/*"

Scenario B:
1. Remove any attached USB drive
2. Open your toolhead and keep the BOOT button pressed
3. Start your printer just normally
4. After 10s release the toolhead's BOOT button
5. Provide the output of "lsusb", "lsblk" and "ls /dev/serial/by-id/*"

There is likely to be an issue with your hardware it is either a bad flash of your toolhead or a bad connection.

**Comment by pmbroth** [comment]
When I updated my toolhead, at first it did not work properly.  For me, I unplegged all usb from the board except the toolhead and then it worked properly.  I know it should have worked piror, but I kept having the flash iussues until I unplugged the other usb devices.

**Comment by Phil1988** [comment]
> I unplugged all usb from the board except the toolhead and then it worked properly. I know it should have worked prior, but I kept having the flash iussues until I unplugged the other usb devices.

This is not necessary. You may have accidentally tried to flash a USB drive or the wifi dongle instead of the actual toolhead. However, unplugging all USB devices can indeed help reduce the chances of making mistakes.

@Caretaker61 Any news on that from your side?

**Comment by Caretaker61** [comment]
Hi Phil,
sorry, for the late answer.

After cd ~/FreeDi && ./install.sh I forgot to make a scrennshot from the output.

Before flasing I had seen the partion with 128 MB and I had this problems before:

![Image](https://github.com/user-attachments/assets/b0c5cd80-6648-45de-afd7-0dfcb7c28d1f)

At the moment I try your scenario A and here the date from

mks@mkspi:~$ lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

mks@mkspi:~$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mmcblk1      179:0    0  28.9G  0 disk
├─mmcblk1p1  179:1    0   256M  0 part /boot
└─mmcblk1p2  179:2    0   6.9G  0 part /var/log.hdd
                                       /
mmcblk1boot0 179:32   0     4M  1 disk
mmcblk1boot1 179:64   0     4M  1 disk
zram0        251:0    0 455.5M  0 disk [SWAP]
zram1        251:1    0    50M  0 disk /var/log
zram2        251:2    0     0B  0 disk


mks@mkspi:~$ ls /dev/serial/by-id/*~
ls: cannot access '/dev/serial/by-id/*~': No such file or directory

I will try now the scenario B

**Comment by Caretaker61** [comment]
Result from scenario B

mks@mkspi:~$ lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 2e8a:0003 Raspberry Pi RP2 Boot
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

mks@mkspi:~$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda            8:0    1   128M  0 disk
└─sda1         8:1    1   128M  0 part
mmcblk1      179:0    0  28.9G  0 disk
├─mmcblk1p1  179:1    0   256M  0 part /boot
└─mmcblk1p2  179:2    0   6.9G  0 part /var/log.hdd
                                       /
mmcblk1boot0 179:32   0     4M  1 disk
mmcblk1boot1 179:64   0     4M  1 disk
zram0        251:0    0 455.5M  0 disk [SWAP]
zram1        251:1    0    50M  0 disk /var/log
zram2        251:2    0     0B  0 disk

mks@mkspi:~$ ls /dev/serial/by-id/*
ls: cannot access '/dev/serial/by-id/*': No such file or directory

**Comment by Phil1988** [comment]
> I had this problems before:
> 
> ![Image](https://github.com/user-attachments/assets/b0c5cd80-6648-45de-afd7-0dfcb7c28d1f)
> 

I absolutely cannot understand that.
I have never used Klipper v0.11 and this screenshot shows that you are completely wrong.

You seem to be mixing up different guides or don't know exactly what you're doing. 
**Where does the OS come from, how did you configure it?**

And from now on, please don't do anything other than what we're discussing, because otherwise it's too time-consuming.

Next steps:
On scenario B your toolhead is in boot mode.
Now please do this:
```
sudo cp ~/FreeDi/Toolhead_RP2040.uf2 /dev/sda1 
```
Shut the system down (sudo shutdown) **and shut it off - switch off or cable disconnected**.
**Wait a few seconds** (at least ~10s) and turn the printer on.

Then do this again:
`ls /dev/serial/by-id/*`

And attach your printer.cfg (as txt file or zipped)
I will be gone for the next ~10h so please be patient if you are still getting errors.

**Comment by Caretaker61** [comment]
I done it.
mks@mkspi:~$ ls /dev/serial/by-id/*
ls: cannot access '/dev/serial/by-id/*': No such file or directory

[printer.zip](https://github.com/user-attachments/files/18468485/printer.zip)

**Comment by Caretaker61** [comment]
Phil,
here's an overview of what I did before I installed your software.
I got the printer, connected it and started it up. I then connected to the printer via a browser and found the programs Klipper, Moonraker with the note “update available” in the “Software” section of the “Fluiid” program interface. As it turned out later, I had carried out the updates by mistake.
I then searched the internet for solutions and found this “GitHub - billkenney_revert_qidi_software_ revert klipper and moonraker to working versions from qidi's repo, and install the latest working version of fluidd” and did it.
QIDI sent me an emmc chip on which the operating system was stored. I exchanged the emmc chips and tried to install the latest firmware provided by QIDI support. When that didn't work either, I installed your software.

**Comment by rosenrot00** [comment]
I try to help a bit, we can solve this. Could you please post the output of everything after you run the commands? you can export these data from the console tool you are using.

In order to start from a common ground, did you install the FreeDi image on your emmc? If not, please do that. Backup your current emmc and overwrite it with the FreeDi image.

When you are in scenario B, you have to flash the toolhead

`sudo cp ~/FreeDi/Toolhead_RP2040.uf2 /dev/sda1 ` isn't 100% what is needed as you need to redirect the path of the uf2 file to where it actually is. Could you verify that the Toolhead_RP2040.uf2 file is somewhere on your system? If so, please change the command accordingly and report the output of this command here.

**Comment by Caretaker61** [comment]
Hi @rosenrot00,
you are german? Then write it in german, please

All steps that you provide, I done it thsi morning.
Do I repeat them ?

**Comment by rosenrot00** [comment]
We can switch to german but if you have discord we should continue our discussion there. Could you share your discord name?

The ping-pong here takes too long.

**Comment by Caretaker61** [comment]
I must create one, wait a minute.

**Comment by Caretaker61** [comment]
I don not know how discord works, but we can try.
My discord name is Caretaker61_82592

**Comment by Caretaker61** [comment]
Hi Phil,
rosenrot00 try to help me, but it failed.
He thinks that the tool head is defective because he could not establish a connection to it.

**Comment by Caretaker61** [comment]
Phil,
I would like to restore the printer to its original state in order to complain about it to QIDI.
Can you please send me the klippers.bin? Version 0.10 was installed.

**Comment by Phil1988** [comment]
> My best guess right now is either: your toolhead is defective or the cable to the toolhead has a loose contact/is faulty.

If rosenrot00 and I share the same opinion, this is most likely the case. I'm sorry to hear that, and I hope Qidi provides you with a replacement.

Find my latest commit and make sure to download them as "raw file":
https://github.com/Phil1988/FreeDi/tree/master/mainboard_and_toolhead_firmwares/v0.10.0-530_stock

Keep us updated on how it goes.

**Comment by Caretaker61** [comment]
Good morning Phil,
the reset almost worked, only the screen shows your start screen, nothing else. Is there a reset routine for that too?

**Comment by pmbroth** [comment]
Have you tried to  access using a browser, based on the ip?  I had this happen, when I had some bad configurations, the display froze on the first screen on the machine.  I then went in via IP and saw the error message, I then used mobaxterm to correct my typo.

**Comment by Phil1988** [comment]
As I'm currently don't have access to my files, I can give you one a link to billkenney 

Please download this:
https://github.com/billkenney/update_max3_plus3/blob/main/800_480_max3_4.3.15.tft

Save in on a SD card.
Switch the printer off.
Insert the SD card to the backside of your screen panel.
Turn the printer on.

Wait until it's flashed.

Switch the printer off.
Remove the SD card.
Turn it on.

**Comment by Phil1988** [comment]
@Caretaker61 the one that I have is a v4.3.12 so it doesnt change much.
Simply use the one from billkenney and please report back.

**Comment by Caretaker61** [comment]
Hi Phil,
I try to install the version from billkenney, but it does not work. After switch one the printer, only the screen shows your start screen, nothing else.

**Comment by Caretaker61** [comment]
Yes, with mobaterm

**Comment by pmbroth** [comment]
If you try to access the machine say with orcaslkicer,  does it connect, and can you look at the device tab, does it show an error?    Review the configurations (Printer.cfg, Macro and mainsail)

**Comment by Caretaker61** [comment]
Yes, for the toolhead, but nothing for the screen on the printer.
mcu 'MKS_THR': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

**Comment by Phil1988** [comment]
As far as I understand this is the current status:
- Stock QIDI OS is flashed on the EMMC
- mainboard MCU is flashed with stock Klipper v0.10.x
- toolhead ist flashed with stock Klipper v0.10.x
- LCD Firmware is still FreeDi and not stock.
- 
@Caretaker61 ist this right?

Make sure your SD card is formatted and it hat the *.TFT file on it that I gave you.
Make sure you have downloaded it as raw file.
To be on the save side, format the SD card with SDFormatter (on windows) and turn adjust option ON

**Comment by Caretaker61** [comment]
Yes, you are right

**Comment by Caretaker61** [comment]
that´s the file

![Image](https://github.com/user-attachments/assets/2e08a01d-deac-4c2a-b5fb-a5d44b62c77d)

**Comment by pmbroth** [comment]
looks good

**Comment by Phil1988** [comment]
format the sd card like this with sdformatter if not already done (turn format size adjustment option ON)
https://github.com/Phil1988/FreeDi/wiki/Requirements#3-microsd-card

**Comment by Caretaker61** [comment]
how long does the updating take?

**Comment by Phil1988** [comment]
flashing the display starts instant after power on.
It takes ~ 2min

**Comment by Caretaker61** [comment]
Phil,

it's not working.

![Image](https://github.com/user-attachments/assets/ed051e4b-f672-4984-bfa4-443ee294c30f)

![Image](https://github.com/user-attachments/assets/196ae18d-9877-4cad-ab88-618e4a32f028)

Could the motherboard be defective?

**Comment by Phil1988** [comment]
No, the problem is you, not the mainboard :D

That's exactly why I wanted the picture.
Insert the SD card into the slot of the display please ;)

**Comment by Phil1988** [comment]
Thanks, mate :)

I'm happy to see you're still learning and haven't lost your motivation. 
Hardware failures are always "unfortunate," and I'm sorry you're dealing with that.

I heard that your printer never worked properly and you got it recently directly from QIDI. I hope they will soon help you out. For me the support was very good and I hope you experience the same.

Just for everyone stumbling across this: 
If your printer has hardware issues, report it to QIDI and ask for replacements. 
Don't convert it to FreeDi, as this can't be resolved. 

As the landing page states: "You're facing hardware issues. FreeDi is software and can't do magic - even if it sometimes still feels magical for me ;)"

**Comment by Demid2297** [comment]
IM having similar issues with mine. I  installed freedi and was running great for a year or so. I had to replace my tool head board. so i updated freedi with the latest. Go through the wizard. it flashes the toolhead. It says it sets everything up correctly but it never boots up. Klippy.log  states
"mcu 'Toolhead': Starting serial connect
mcu 'Toolhead': Unable to open serial port: [Errno 2] could not open port /dev/serial/by-id/usb-Klipper_rp2040_35AE7A9652FF5E53-if00: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-Klipper_rp2040_35AE7A9652FF5E53-if00'  "

im out of ideas. Any help? Im sure its user error, what am i doing wrong. Please help

**Comment by Caretaker61** [comment]
Hello Phil,

here I am again with another problem.

I installed your FreeDi 2.08 release and everything worked wonderfully. However, after restarting Klipper, the system can no longer find the tool head. I have attached various logs for you.

Can you help, please.

Kind Regards
Hartmut

[klippy.log](https://github.com/user-attachments/files/25578629/klippy.log)
[moonraker.log](https://github.com/user-attachments/files/25578628/moonraker.log)

<img width="866" height="931" alt="Image" src="https://github.com/user-attachments/assets/8eda207b-3709-475c-a244-96add609ee3d" />

**Comment by Phil1988** [comment]
Hey @Caretaker61 (Hartmut), please try not to mix issues up in the future - especially not on already closed issues as I consider them es closed/finished ;)

Your issue should be solvable by simply (re)flash the mainboard MCU using the microSD card and the X_4.bin file.
Cheers!
